name: Build Natives

on: [push, workflow_dispatch]

jobs:
  buildLinux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: sudo apt install g++-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 gcc-mingw-w64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 libasound2-dev
    - name: Set env
      run: echo "NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
    - name: Build natives
      run: |
        ./gradlew arc-core:jar
        ./gradlew arc-core:jnigenBuild
    - name: Upload natives
      uses: actions/upload-artifact@v2
      with:
        name: Arc-core desktop natives
        path: |
          natives/natives-desktop/libs/libarc64.so
          natives/natives-desktop/libs/arc.dll
          natives/natives-desktop/libs/arc64.dll
    - name: Upload Android natives
      uses: actions/upload-artifact@v2
      with:
        name: Arc-core android natives
        path: |
          natives/natives-android/libs
  buildMac:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #- name: Install dependencies
    #  run: sudo brew install g++-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 gcc-mingw-w64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 libasound2-dev
    - name: Build natives
      run: |
        ./gradlew arc-core:jar
        ./gradlew arc-core:jnigenBuild
    - name: Upload natives
      uses: actions/upload-artifact@v2
      with:
        name: Arc-core MacOS natives
        path: |
          natives/natives-desktop/libs/libarc64.dylib
    - name: Upload iOS natives
      uses: actions/upload-artifact@v2
      with:
        name: Arc-core iOS natives
        path: |
          natives/natives-ios/libs/libarc.a