name: Build Natives

on: [workflow_dispatch]

jobs:
  buildMac:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install dependencies
        run: |
          brew install sdl2
          brew install glew
      - name: Build natives
        run: |
          ./gradlew backends:backend-sdl:jnigenBuild
      - name: Upload natives
        uses: actions/upload-artifact@v2
        with:
          name: Arc-core MacOS natives
          path: |
            natives/natives-desktop/libs/libarc64.dylib
            natives/natives-freetype-desktop/libs/libarc-freetype64.dylib
            backends/backend-sdl/libs/macosx64/libsdl-arc64.dylib
      - name: Upload iOS natives
        uses: actions/upload-artifact@v2
        with:
          name: Arc-core iOS natives
          path: |
            natives/natives-ios/libs/libarc.a
            natives/natives-freetype-ios/libs/libarc-freetype.a